[general]
chat_models = ["gpt-3.5-turbo", "gpt-4"]
model = "gpt-3.5-turbo"
temperature = 0

[prompts]
instruction_prompt = """
Remove personally identifiable information, only show the date,
and replace all swear words with "😤"
"""
role_prompt = """
"""
positive_example = """
"""
positive_reasoning = """
"""
positive_output = """
"""
negative_example = """
"""
negative_reasoning = """
"""
negative_output = """
"""
